POST http://localhost:3000/auth/signup
content-type: application/json

{
    "phone": "77073816081",
    "password": "qwerrt",
}

### Set a color
GET http://localhost:3000/auth/colors/blue

### Get the color
GET http://localhost:3000/auth/colors

