POST http://localhost:3000/auth/signup
content-type: application/json

{
    "phone": "87027568921",
    "password": "supertest"
}
### 
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "phone": "87027568921",
    "password": "supertest"
}

### Set a color
GET http://localhost:3000/auth/colors/blue

### Get the color
GET http://localhost:3000/auth/colors

### Who am I
GET http://localhost:3000/auth/whoami

### Logout
POST http://localhost:3000/auth/signout